---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocm-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 10m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/flux/ocm-controller
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 10m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/flux/cert-manager
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 10m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/flux/config
  prune: true
