version: "2"
run:
  go: "1.22"
  tests: false
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - govet
    - ireturn
    - nilnil
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - staticcheck
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - funcorder
    - recvcheck
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 150
      statements: 60
    lll:
      line-length: 150
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    varnamelen:
      ignore-names:
        - err
        - wg
        - fs
        - id
        - vm
        - ns
        - ip
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - golint
        text: should not use dot imports|don't use an underscore in package name
      - linters:
          - lll
        source: https://
      - linters:
          - lll
        path: pkg/defaults/
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - godox
          - gosec
          - scopelint
          - testpackage
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: internal/version/
      - linters:
          - exhaustivestruct
          - lll
          - wrapcheck
        path: internal/command/
      - linters:
          - godox
        source: '// .* #\d+'
      - linters:
          - err113
          - mnd
        path: test/e2e/
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - pkg/ocm/fakes/fakes.go
      - pkg/cache/fakes/cache.go
      - pkg/untar/untar.go
      - ./*/mock
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/ocm/fakes/fakes.go
      - pkg/cache/fakes/cache.go
      - pkg/untar/untar.go
      - ./*/mock
      - third_party$
      - builtin$
      - examples$
