apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-controller
  labels:
    control-plane: controller
    app: ocm-controller
spec:
  selector:
    matchLabels:
      app: ocm-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: ocm-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --zap-log-level=4
        - --leader-elect
        - --oci-registry-addr=registry.ocm-system.svc.cluster.local:5000
        image: open-component-model/ocm-controller
        name: manager
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: ocm-controller
      terminationGracePeriodSeconds: 10
