apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

# Uncomment to enable HTTPS for the registry
patches:
- path: ./patches/add_registry_certificates.yaml
