apiVersion: v1
kind: Service
metadata:
  name: ocm-controller-metrics
  labels:
    app: ocm-controller
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: ocm-controller-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: ocm-controller
    app.kubernetes.io/part-of: ocm-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    app: ocm-controller
