{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ocm-bootstrap-issuer
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocm-bootstrap-certificate
  namespace: cert-manager
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # needs to happen AFTER the job run successfully
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-ocm-tls
  isCA: true
  secretName: ocm-registry-tls-certs
  subject:
    organizations:
      - ocm.software
  dnsNames:
    - registry.ocm-system.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: ocm-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ocm-certificate-issuer
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  ca:
    secretName: ocm-registry-tls-certs
{{- end}}
