apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller
    app: ocm-controller
spec:
  selector:
    matchLabels:
      app: ocm-controller
  replicas: {{ .Values.manager.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: ocm-controller
    spec:
      imagePullSecrets: {{ $.Values.manager.image.imagePullSecrets | toJson }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --zap-log-level=4
        - --leader-elect
        - --oci-registry-addr={{ .Values.registry.address }}
        {{- if not .Values.registry.tls.enabled }}
        - --oci-registry-insecure-skip-verify
        {{- end }}
        image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
        name: manager
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        {{- if .Values.registry.tls.enabled }}
        volumeMounts:
        {{- toYaml .Values.manager.volumeMounts | nindent 10 }}
        {{- end}}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- toYaml .Values.manager.resources | nindent 10 }}
      serviceAccountName: ocm-controller
      terminationGracePeriodSeconds: 10
      {{- if .Values.registry.tls.enabled }}
      volumes:
      {{- toYaml .Values.manager.volumes | nindent 8 }}
      {{- end}}
      {{- if .Values.manager.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.manager.nodeSelector | nindent 8 }}
      {{- end}}
