{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocm-registry-tls-certs
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # needs to be applied after the wait for cert-manager job run successfully
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: ocm-registry-tls-certs
  dnsNames:
    - registry.ocm-system.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: ocm-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end}}
