apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
