{{- if index .Values "cert-manager" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wait-for-cert-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: wait-for-cert-manager-sa
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: wait-for-cert-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end}}
