# permissions for end users to edit resourcepipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcepipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocm-controller
    app.kubernetes.io/part-of: ocm-controller
    app.kubernetes.io/managed-by: kustomize
  name: resourcepipeline-editor-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - resourcepipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - resourcepipelines/status
  verbs:
  - get
