apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ocm-controller
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/open-component-model/helm/ocm-controller
  ref:
    semver: "v0.24.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm-controller
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ocm-controller
  install:
    createNamespace: true
  targetNamespace: ocm-system
