---
apiVersion: v1
kind: Namespace
metadata:
  name: ocm-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ocm-controller
  namespace: ocm-system
spec:
  interval: 15m
  type: "oci"
  url: oci://ghcr.io/open-component-model/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm
  namespace: ocm-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ocm-controller
      version: "v0.24.0"
      sourceRef:
        kind: HelmRepository
        name: ocm-controller
        namespace: ocm-system
      interval: 12h
  values:
    cert-manager:
      enabled: false
