apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: deployer
  namespace: ocm-system
spec:
  sourceRef:
    kind: ResourcePipeline
    name: pipeline
  kustomizationTemplate:
    interval: 1m0s
    path: ./
    prune: true
    targetNamespace: default
