apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes
  namespace: ocm-system
spec:
  provider:
    kubernetes:
      remoteNamespace: ocm-system
      server:
        # url: http://localhost:8001
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: secret-reader
---
