# Generate TLS Certificate for registry and manager 
tlsCert:
  # If cert-manager is installed, set generateTlsCert to true to generate a cert
  generateTlsCert: false
  defaultSecretName: &tlsSecretName "ocm-registry-tls-certs"
  defaultIssuerName: "ocm-certificate-issuer"

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
registry:
  image:
    repository: registry
    pullPolicy: IfNotPresent
    tag: 3
    imagePullSecrets:
  address: registry.ocm-system.svc.cluster.local:5000
  tls:
    enabled: true
    env:
      - name: REGISTRY_HTTP_TLS_CERTIFICATE
        value: "/certs/cert.pem"
      - name: REGISTRY_HTTP_TLS_KEY
        value: "/certs/key.pem"
    volumeMounts:
      - mountPath: "/certs"
        name: *tlsSecretName
    volumes:
      - name: *tlsSecretName
        secret:
          secretName: *tlsSecretName
          items:
            - key: "tls.crt"
              path: "cert.pem"
            - key: "tls.key"
              path: "key.pem"
            - key: "ca.crt"
              path: "ca.pem"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  nodeSelector: {}

manager:
  replicaCount: 1
  image:
    repository: ghcr.io/open-component-model/ocm-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    imagePullSecrets:
  volumeMounts:
    - mountPath: "/etc/ssl/certs/registry-root.pem"
      subPath: "registry-root.pem"
      name: "certificates"

  volumes:
    - name: "certificates"
      secret:
        secretName: *tlsSecretName # must match with ocm-controller's certificate-secret-name argument
        items:
          - key: "ca.crt"
            path: "registry-root.pem"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  # optional values defined by the user
  nodeSelector: {}
  tolerations: []
  affinity: {}
  clusterRole:
    labels:

monitoring:
  enabled: false
