apiVersion: delivery.ocm.software/v1alpha1
kind: ResourcePipeline
metadata:
  name: resolver
spec:
  interval: 10m0s
  sourceRef:
    name: podinfo
    namespace: default
    resource: manifests
  pipelineSpec:
    steps:
      - name: resolve
        module: ocm.software/delivery:v1.0.0@resolver
