apiVersion: delivery.ocm.software/v1alpha1
kind: ResourcePipeline
metadata:
  name: resolver
  namespace: ocm-system
spec:
  interval: 10m0s
  sourceRef:
    name: podinfo
    namespace: ocm-system
    resource: manifests
  secrets:
    k8s:
      remoteRef:
        key: test-secret
        property: token
      secretStoreRef:
        name: test-secret-store
        namespace: ocm-system
  pipelineSpec:
    steps:
      - name: resolve
        module: ocm.software/delivery:v1.0.0@resolver
