apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: carts
spec:
  interval: 1m0s
  componentVersionRef:
    name: nested-component
    namespace: default
  source:
    sourceRef:
      kind: Snapshot
      name: carts-manifests
      namespace: default
  configRef:
    resource:
      resourceRef:
        name: config
        referencePath:
          - name: carts
  snapshotTemplate:
    name: carts-manifests-localized
    tag: latest
