apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: resource-backend
  namespace: ocm-system
spec:
  interval: 1m
  sourceRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: deployment
      version: 1.0.0
