apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: test-secret-store
  namespace: ocm-system
spec:
  provider:
    kubernetes:
      remoteNamespace: ocm-system
      auth:
        serviceAccount:
          name: "ocm-controller"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
