apiVersion: delivery.ocm.software/v1alpha1
kind: Configuration
metadata:
  name: carts
spec:
  interval: 1m0s
  sourceRef:
    kind: Snapshot
    name: carts-manifests-localized
    namespace: default
  configRef:
    componentVersionRef:
      name: nested-component
      namespace: default
    resource:
      name: config
      referencePath:
        name: carts
  snapshotTemplate:
    name: carts-manifests-configured
    tag: latest
  values:
    color: "blue"
    message: "Hola"
