apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: carts-manifests
spec:
  interval: 1m0s
  componentVersionRef:
    name: nested-component
    namespace: default
  resource:
    name: manifests
    referencePath:
      name: carts
  snapshotTemplate:
    name: carts-manifests
    tag: latest
