---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ocm-system
    app.kubernetes.io/part-of: ocm
  name: ocm-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocm-controller-manager-role
subjects:
- kind: ServiceAccount
  name: ocm-controller
  namespace: ocm-system
