---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocm-system
    app.kubernetes.io/part-of: ocm
  name: registry
  namespace: ocm-system
spec:
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
  selector:
    app: registry
