apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-controller
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: ocm-controller
  template:
    spec:
      # TODO: Add the Secret volume mount for the dev certificate secret.
