apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: phoban.io/test/podinfo
  version:
    semver: "v1.0.0"
  repository:
    url: ghcr.io/phoban01
  serviceAccountName: ocm
