apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: podinfo-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  sourceRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: manifests
      version: latest
  middleware:
  - name: ocm-localizer
    component: delivery.ocm.software/mutators:v1.0.0
    values:
      prefix: "ocm://"
