apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: monolith
spec:
  interval: 10m0s
  component: ocm.software/monolith
  version:
    semver: ">=v1.3.0"
  repository:
    url: ghcr.io/open-component-model
    secretRef:
      name: creds
  verify:
  - name: default
    publicKey:
      secretRef:
        name: publickey
  references:
    expand: true
