name: Scan Pull Request Activity

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  issues: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.OCMBOT_APP_ID }}
          private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
      - name: scan pull request activity
        uses: skarlso/caretaker@v0.6.0
        with:
          command: scan
          owner: open-component-model
          repo: ocm-controller
          isOrganization: true
          token: ${{ steps.generate_token.outputs.token }}
          statusOption: 👀 In review
          pullRequestProcessedLabel: caretaker-checked # a label to mark the pull request as seen