name: Check for diff after manifest and generated targets

on:
  pull_request: {}

permissions:
  contents: read
    
jobs:
  diff-check-manifests:
    name: Check for diff
    runs-on: ubuntu-latest
    steps:
    - name: Self Hosted Runner Post Job Cleanup Action
      uses: TooMuch4U/actions-clean@9b358e33df99574ac0bdf2e92fa3db1ae1415563
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: Make manifests && generate
      run: |
        make manifests && make generate
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version-file: '${{ github.workspace }}/go.mod'
    - name: Restore Go cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: /home/runner/work/_temp/_github_home/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go mod tidy
      run: |
        go mod tidy
    - name: Check for diff
      run: |
        git diff --exit-code --shortstat
