name: component CTFs

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  build-cli:
    name: Build component
    runs-on: large_runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - name: CTF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd component/
          PATH=$PATH:$(go env GOPATH)/bin make ocm && make ctf && make push
